pipeline {
    agent none
    stages {
        stage('Deploy to Kubernetes') {
            when {
                changeset "**/iac/*.yaml"
            }
        
        agent {
            kubernetes {
                defaultContainer 'kubectl'
                yaml """
kind: Pod
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 1000
  containers:
  - name: kubectl
    image: jitesoft/kubectl:v1.28
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
"""
                }
            }

            steps {
                container('kubectl') {
                    sh 'kubectl apply -f iac/yaml'
                }
            }
        }
    }
}
