pipeline {
    agent none
    stages {
        stage('Deploy to Kubernetes') {
            when {
                changeset "**/iac/*.yaml"
            }
        
        agent {
            kubernetes {
                defaultContainer 'kubectl'
                yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
app: kubectl
spec:
serviceAccountName: jenkins
containers:
- name: kubectl
image: jitesoft/kubectl:v1.28
command:
command:
- sleep
args:
- 99d
"""
                }
            }

            steps {
                container('kubectl') {
                    sh 'kubectl apply -f iac/yaml'
                }
            }
        }
    }
}
